apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: msg
  name: messaging-pod-liran
spec:
  containers:
  - image: redis:alpine
    name: messaging-pod-liran
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
