apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-yourname
spec:
  containers:
  - image: nginx
    name: use-pv
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: /data
  volumes:
  - name: pv-1
    persistentVolumeClaim:
      claimName: pv-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
