apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: alpha
      image: nginx
      env:
        - name: CONTAINER_NAME
          value: alpha
    - name: beta
      image: busybox
      command: ["sleep", "4800"]
      env:
        - name: CONTAINER_NAME
          value: beta
