apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-06-26T17:15:03Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: 754bcc647d
    name: webapp-754bcc647d
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: 7766084e-a5b8-4283-936a-be8c9c855521
    resourceVersion: "86702"
    uid: f30d0468-1e4c-4d8b-b2bf-121b48355a40
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 754bcc647d
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 754bcc647d
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
