apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - redis-storage-liran
    image: redis:alpine
    name: pod
    resources: {}
    volumeMounts:
      - mountPath: /data/redis
        name: redis-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: redis-volume
      emptyDir: {}   
status: {}
